import puppeteer from 'puppeteer-core';
const EDGE = 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe';
const b = await puppeteer.launch({ executablePath: EDGE, headless: 'new', args: ['--no-sandbox', '--disable-gpu'] });
const pg = await b.newPage();
await pg.setViewport({ width: 1440, height: 1000 });
await pg.goto('https://www.carismaslimming.com/fatdissolving', { waitUntil: 'networkidle2', timeout: 60000 }).catch(() => {});
await new Promise((r) => setTimeout(r, 3000));
const srcs = await pg.evaluate(() => Array.from(document.querySelectorAll('img')).map((i) => ({ y: Math.round(i.getBoundingClientRect().top + window.scrollY), src: i.currentSrc || i.src })));
for (const s of srcs) console.log(s.y, s.src);
await b.close();
